import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const shareTech = localFont({
  src: '../public/ShareTech-Regular.ttf',
  variable: '--font-share-tech',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={shareTech.variable}>{children}</body>
    </html>
  );
}
